services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ModernaBundle\Controller\:
        resource: '../../src/Controller'
        tags: ['controller.service_arguments']

    # API controllers
    ModernaBundle\Api\:
        resource: '../../src/Api'
        tags: ['controller.service_arguments']

    # Twig extensions
    ModernaBundle\Twig\CartExtension:
        tags: ['twig.extension']

    ModernaBundle\Twig\CartIsolationExtension:
        tags: ['twig.extension']

    ModernaBundle\Twig\TaxedPriceExtension:
        tags: ['twig.extension']

    ModernaBundle\Twig\HeaderHighlightsExtension:
        tags: ['twig.extension']

    ModernaBundle\Twig\LanguageExtension:
        tags: ['twig.extension']

    # Event subscribers
    ModernaBundle\EventSubscriber\LanguagePersistenceSubscriber:
        tags: ['kernel.event_subscriber']

    # UI Components
    ModernaBundle\UiComponents\LangSelect\LangSelect:
        tags: ['twig.component']

    ModernaBundle\UiComponents\Product\ProductCard:
        tags: ['twig.component']
